name: Deploy Documentation to Documentation Branch

on:
  push:
    branches: [ documentation ]
  pull_request:
    branches: [ documentation ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install sphinx-rtd-theme

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Deploy to documentation branch
        run: |
          # Configure git
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create .nojekyll file in the docs/_build/html directory
          touch docs/_build/html/.nojekyll
          
          # Force add the built documentation (ignored by .gitignore)
          git add -f docs/_build/html/
          git add -f docs/_build/html/.nojekyll
          
          # Commit the changes
          git commit -m "Deploy documentation from ${{ github.sha }}"
          
          # Push to documentation branch
          git push origin HEAD:documentation 